<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Product>SiteLink.Queue</Product>
		<Description>Adds translated queue worlds and priority connection flow to SiteLink.</Description>
		<Authors>Killers0992</Authors>
		<Version>1.2.0</Version>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.Protobuf" Version="3.33.0" />
		<PackageReference Include="Grpc.Core" Version="2.46.6" />
		<PackageReference Include="Grpc.Tools" Version="2.46.6" PrivateAssets="All" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
		<PackageReference Include="SiteLink.API" Version="0.0.3" Condition="'$(Configuration)' == 'Release'" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Grpc/Protos/common.proto" GrpcServices="Client" />
		<Protobuf Include="Grpc/Protos/proxyserver.proto" GrpcServices="Client" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\SiteLink\SiteLink.API\SiteLink.API.csproj"
	                    SetTargetFramework="TargetFramework=net10.0" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Translations\language_en.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Mirror">
			<HintPath>$(SL_REFERENCES)\Mirror.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(UNITY_REFERENCES)\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<MakeDir Directories="D:\VS Projects\SiteLink\SiteLink\bin\Debug\net10.0\win-x64\Plugins\Queue\Translations" Condition="'$(Configuration)' == 'Debug'" />
		<Copy SourceFiles="$(TargetDir)$(TargetName).dll" Condition="'$(Configuration)' == 'Debug'" DestinationFolder="D:\VS Projects\SiteLink\SiteLink\bin\Debug\net10.0\win-x64\Plugins" />
		<Copy SourceFiles="@(QueueTranslationFiles)" Condition="'$(Configuration)' == 'Debug'" DestinationFolder="D:\VS Projects\SiteLink\SiteLink\bin\Debug\net10.0\win-x64\Plugins\Queue\Translations" />
	</Target>

	<ItemGroup>
		<QueueTranslationFiles Include="Translations\*.json" />
	</ItemGroup>

</Project>
